name: On pull request

on:
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'corretto'

    - name: Commitlint and Other Shared Build Steps
      uses: momentohq/standards-and-practices/github-actions/shared-build@gh-actions-v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-momento:
    runs-on: ubuntu-latest
    env:
      MOMENTO_API_KEY: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}

    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'corretto'

    - name: Commitlint and Other Shared Build Steps
      uses: momentohq/standards-and-practices/github-actions/shared-build@gh-actions-v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build project
      run: make build

    - name: Run tests
      run: make test

  test-redis:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    env:
      MOMENTO_API_KEY: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}

    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'corretto'

    - name: Commitlint and Other Shared Build Steps
      uses: momentohq/standards-and-practices/github-actions/shared-build@gh-actions-v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build project
      run: make build

    - name: Run tests
      run: REDIS=1 make test
